# Generated by Django 3.1.7 on 2023-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='arrivalLoc_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='arrivalLoc_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='currentLoc_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='currentLoc_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
